include:
  - elastic.compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tacs-backend
    ports:
      - ${BACKEND_PORT:-8080}:8080
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:?}
      - ELASTIC_URL=es01:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:?}
      - ELASTIC_CA_CERT_PATH=/home/appuser/certs/es01/es01.crt
    volumes:
      - certs:/home/appuser/certs:ro
    user: appuser
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
