include:
  - backend.compose.yml

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tacs-web
    ports:
      - ${PORT:-3000}:3000
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - BASE_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
