services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tacs-web
    ports:
      - ${PORT:-8080}:8080
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:?}
#    depends_on:
#      db:
#        condition: service_healthy

#  db:
#    image: tbd
#    container_name: tacs-db
#    ports:
#      - tbd
#    environment:
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-postgres}"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
